/**
 * Portfolio component
 *
 * Highlights some of  your creations. These can be designs, websites,
 * open source contributions, articles you've written and more.
 *
 * This is a great area for you to to continually add to and refine
 * as you continue to learn and create.
 */

import React from "react";

/**
 * Desk image
 *
 * Below is a sample desk image. Feel free to update this to an image of your choice,
 * updating below imageAltText to string that represents what you see in that image.
 *
 * Need an image? Check out https://unsplash.com to download a photo you
 * freely use on your site.
 */
import image from "../images/programmer.jpg";

const imageAltText = "vector picture with laptop and User interface";

/**
 * Project list
 *
 * An array of objects that will be used to display for your project
 * links section. Below is a sample, update to reflect links you'd like to highlight.
 */
const projectList = [
  {
    title: "Simple Quote Generator🎉",
    description:
      "Created a web app that generates single random Quotation using HTML, CSS, and JS",
    url: "https://imjavahater.github.io/kntquotegen.github.io/",
  },
  {
    title: "Infinite Scroll API",
    description:
      "These help provide visual representation of random images generated by the unsplash API.",
    url: "https://imjavahater.github.io/js-infnt-scrl/",
  },
  {
    title: "Interactive Kendrypto Website",
    description:
      "Created using JS, HTML, and CSS, this is for the future reference for building an interactive-gradient website.",
    url: "https://imjavahater.github.io/interactive-crypto-web/",
  },
  {
    title: "Introductory of my Github",
    description:
      "A landing page to my sole Github page showing my priorities in tech-stacks and commits.",
    url: "https://github.com/imjavahater/imjavahater",
  },
];

const Portfolio = () => {
  return (
    <section className="padding" id="portfolio">
      <h2 style={{ textAlign: "center" }}>Portfolio</h2>
      <div style={{ display: "flex", flexDirection: "row", paddingTop: "3rem" }}>
        <div style={{ maxWidth: "40%", alignSelf: "center" }}>
          <img
            src={image}
            style={{ height: "90%", width: "100%", objectFit: "cover" }}
            alt={imageAltText}
          />
        </div>
        <div className="container">
          {projectList.map((project) => (
            <div className="box" key={project.title}>
              <a href={project.url} target="_blank" rel="noopener noreferrer">
                <h3 style={{ flexBasis: "40px" }}>{project.title}</h3>
              </a>
              <p className="small">{project.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Portfolio;
